// ============================================================
// おむすびぱんだ omp001〜120 料理名マスターデータ
// 画像ファイル名: omp001.png 〜 omp120.png
//
// 使い方:
//   import { OMP_FOOD_LIST } from "./omp_food_data.js";
//
// 各アイテムのフィールド:
//   id     : number   — 連番 (1〜120)
//   file   : string   — 画像ファイル名 (例: "omp001.png")
//   name   : string   — 日本語料理名
//   nameEn : string   — 英語料理名
// ============================================================

export const OMP_FOOD_LIST = [
  { id:   1, file: "omp001.png", name: "笹、はじめての味",                   nameEn: "Bamboo Leaf, First Taste" },
  { id:   2, file: "omp002.png", name: "にくまん、あつい",                   nameEn: "Steamed Meat Bun, Piping Hot" },
  { id:   3, file: "omp003.png", name: "うどん、ずるずる",                   nameEn: "Udon Noodles, Slurp Slurp" },
  { id:   4, file: "omp004.png", name: "オムライス、ふわふわ",               nameEn: "Omurice, Fluffy" },
  { id:   5, file: "omp005.png", name: "餃子、ぱくぱく",                     nameEn: "Gyoza, Munch Munch" },
  { id:   6, file: "omp006.png", name: "ラーメン、濃厚",                     nameEn: "Ramen, Rich & Bold" },
  { id:   7, file: "omp007.png", name: "焼き鳥、じゅーしー",                 nameEn: "Yakitori, Juicy" },
  { id:   8, file: "omp008.png", name: "とんかつ、サクサク",                 nameEn: "Tonkatsu, Crispy" },
  { id:   9, file: "omp009.png", name: "ピザ、とろける",                     nameEn: "Pizza, Melty" },
  { id:  10, file: "omp010.png", name: "グラノーラ、さくさく",               nameEn: "Granola, Crunchy" },
  { id:  11, file: "omp011.png", name: "たこやき、あつあつ",                 nameEn: "Takoyaki, Steaming Hot" },
  { id:  12, file: "omp012.png", name: "おでん、しみしみ",                   nameEn: "Oden, Deeply Flavored" },
  { id:  13, file: "omp013.png", name: "からあげ、じゅーしー",               nameEn: "Karaage, Juicy" },
  { id:  14, file: "omp014.png", name: "おにぎり、ほっこり",                 nameEn: "Onigiri, Comforting" },
  { id:  15, file: "omp015.png", name: "さば味噌、こっくり",                 nameEn: "Saba Miso, Hearty" },
  { id:  16, file: "omp016.png", name: "カレー、スパイシー",                 nameEn: "Curry, Spicy" },
  { id:  17, file: "omp017.png", name: "エビフライ、サクサク！",             nameEn: "Fried Shrimp, Super Crispy!" },
  { id:  18, file: "omp018.png", name: "たこぶつ、ぷりぷり。",               nameEn: "Octopus Chunks, Springy." },
  { id:  19, file: "omp019.png", name: "サラダ、ヘルシー！",                 nameEn: "Salad, Healthy!" },
  { id:  20, file: "omp020.png", name: "マグロ寿司、とろける。",             nameEn: "Tuna Sushi, Melt-in-Your-Mouth." },
  { id:  21, file: "omp021.png", name: "ホットドッグ、アメリカン！",         nameEn: "Hot Dog, All-American!" },
  { id:  22, file: "omp022.png", name: "クロワッサン、サクサク。",           nameEn: "Croissant, Flaky." },
  { id:  23, file: "omp023.png", name: "ハンバーガー、食べごたえ！",         nameEn: "Hamburger, Hearty!" },
  { id:  24, file: "omp024.png", name: "てんぷら巻き、衣がうまい。",         nameEn: "Tempura Roll, Crispy Batter." },
  { id:  25, file: "omp025.png", name: "ナポリタン、昔ながらの味！",         nameEn: "Napolitan Spaghetti, Classic Taste!" },
  { id:  26, file: "omp026.png", name: "フライドポテト、止まらない。",       nameEn: "French Fries, Can't Stop Eating." },
  { id:  27, file: "omp027.png", name: "豚骨らーめん、濃厚！",               nameEn: "Tonkotsu Ramen, Rich & Creamy!" },
  { id:  28, file: "omp028.png", name: "焼きおにぎり、香ばしい。",           nameEn: "Grilled Onigiri, Fragrant." },
  { id:  29, file: "omp029.png", name: "ステーキ、ジューシー！",             nameEn: "Steak, Juicy!" },
  { id:  30, file: "omp030.png", name: "小籠包、あつあつ。",                 nameEn: "Xiao Long Bao, Piping Hot." },
  { id:  31, file: "omp031.png", name: "タコス、本格派！",                   nameEn: "Tacos, Authentic!" },
  { id:  32, file: "omp032.png", name: "アヒージョ、オリーブオイル。",       nameEn: "Ajillo, Olive Oil." },
  { id:  33, file: "omp033.png", name: "ベーグル、もちもち！",               nameEn: "Bagel, Chewy!" },
  { id:  34, file: "omp034.png", name: "焼肉、あつあつ。",                   nameEn: "Yakiniku, Sizzling Hot." },
  { id:  35, file: "omp035.png", name: "パエリア、具だくさん！",             nameEn: "Paella, Loaded with Ingredients!" },
  { id:  36, file: "omp036.png", name: "ホットパイ、さくさく。",             nameEn: "Hot Pie, Crispy." },
  { id:  37, file: "omp037.png", name: "やきいも、ほっくり！",               nameEn: "Baked Sweet Potato, Fluffy!" },
  { id:  38, file: "omp038.png", name: "キューバンサンド、絶品。",           nameEn: "Cuban Sandwich, Exquisite." },
  { id:  39, file: "omp039.png", name: "チーズ、濃厚！",                     nameEn: "Cheese, Rich!" },
  { id:  40, file: "omp040.png", name: "ローストビーフ、贅沢。",             nameEn: "Roast Beef, Luxurious." },
  { id:  41, file: "omp041.png", name: "そば、ツルツル！",                   nameEn: "Soba Noodles, Silky Smooth!" },
  { id:  42, file: "omp042.png", name: "鯛蒲焼、香ばしい！",                 nameEn: "Grilled Sea Bream, Fragrant!" },
  { id:  43, file: "omp043.png", name: "カツ丼＆お好み焼き、ミニセット。",   nameEn: "Katsudon & Okonomiyaki, Mini Set." },
  { id:  44, file: "omp044.png", name: "ブッラータ、とろける！",             nameEn: "Burrata, Melty!" },
  { id:  45, file: "omp045.png", name: "バインミー、ヘルシー。",             nameEn: "Bánh Mì, Healthy." },
  { id:  46, file: "omp046.png", name: "リゾット、濃厚！",                   nameEn: "Risotto, Creamy!" },
  { id:  47, file: "omp047.png", name: "クラブハウスサンド、ボリューム。",   nameEn: "Club House Sandwich, Filling." },
  { id:  48, file: "omp048.png", name: "チーズフォンデュ、アツアツ！",       nameEn: "Cheese Fondue, Piping Hot!" },
  { id:  49, file: "omp049.png", name: "ひばち焼き、じゅうじゅう。",         nameEn: "Hibachi Grill, Sizzle Sizzle." },
  { id:  50, file: "omp050.png", name: "巻寿司、ボリューム満点！",           nameEn: "Maki Sushi, Packed Full!" },
  { id:  51, file: "omp051.png", name: "ちらし寿司、彩り鮮やか！",           nameEn: "Chirashi Sushi, Colorful!" },
  { id:  52, file: "omp052.png", name: "麻婆豆腐、ピリ辛！",                 nameEn: "Mapo Tofu, Spicy!" },
  { id:  53, file: "omp053.png", name: "ひやむぎ、さっぱり！",               nameEn: "Hiyamugi Noodles, Refreshing!" },
  { id:  54, file: "omp054.png", name: "塩辛、通の味！",                     nameEn: "Shiokara, Connoisseur's Flavor!" },
  { id:  55, file: "omp055.png", name: "枝豆、おつまみ最高！",               nameEn: "Edamame, Best Snack!" },
  { id:  56, file: "omp056.png", name: "和牛握り寿司、とろける！",           nameEn: "Wagyu Nigiri Sushi, Melt-in-Your-Mouth!" },
  { id:  57, file: "omp057.png", name: "お茶漬け、あっさり！",               nameEn: "Ochazuke, Light & Simple!" },
  { id:  58, file: "omp058.png", name: "白ご飯おおもり、満足！",             nameEn: "Large Bowl of White Rice, Satisfying!" },
  { id:  59, file: "omp059.png", name: "味噌汁、ホッとする！",               nameEn: "Miso Soup, Comforting!" },
  { id:  60, file: "omp060.png", name: "サンドイッチ、具沢山！",             nameEn: "Sandwich, Loaded!" },
  { id:  61, file: "omp061.png", name: "パンプキンスープ、まろやか！",       nameEn: "Pumpkin Soup, Smooth & Creamy!" },
  { id:  62, file: "omp062.png", name: "納豆ごはん、ネバネバ！",             nameEn: "Natto Rice, Sticky!" },
  { id:  63, file: "omp063.png", name: "うな重、ご馳走！",                   nameEn: "Unaju, Feast!" },
  { id:  64, file: "omp064.png", name: "七輪で焼いたさんま、絶品！",         nameEn: "Grilled Saury on Shichirin, Exquisite!" },
  { id:  65, file: "omp065.png", name: "フランクフルト、ジューシー！",       nameEn: "Frankfurt Sausage, Juicy!" },
  { id:  66, file: "omp066.png", name: "アメリカンドッグ、ふかふか！",       nameEn: "Corn Dog, Fluffy!" },
  { id:  67, file: "omp067.png", name: "チャーハン、パラパラ！",             nameEn: "Fried Rice, Fluffy & Loose!" },
  { id:  68, file: "omp068.png", name: "焼きそば、香ばしい！",               nameEn: "Yakisoba, Fragrant!" },
  { id:  69, file: "omp069.png", name: "メンチカツ、サクサク！",             nameEn: "Menchi Katsu, Crispy!" },
  { id:  70, file: "omp070.png", name: "親子丼、とろとろ！",                 nameEn: "Oyakodon, Silky!" },
  { id:  71, file: "omp071.png", name: "牛丼、こってり！",                   nameEn: "Gyudon, Rich!" },
  { id:  72, file: "omp072.png", name: "コロッケ、ほくほく！",               nameEn: "Croquette, Fluffy Inside!" },
  { id:  73, file: "omp073.png", name: "タピオカミルクティー、もちもち！",   nameEn: "Bubble Milk Tea, Chewy!" },
  { id:  74, file: "omp074.png", name: "紅茶とドーナツ、あまい！",           nameEn: "Tea & Donut, Sweet!" },
  { id:  75, file: "omp075.png", name: "コーヒーとトースト、ほっくり！",     nameEn: "Coffee & Toast, Cozy!" },
  { id:  76, file: "omp076.png", name: "ビールと焼き鳥、最高！",             nameEn: "Beer & Yakitori, The Best!" },
  { id:  77, file: "omp077.png", name: "ワインとチーズ、濃厚！",             nameEn: "Wine & Cheese, Rich!" },
  { id:  78, file: "omp078.png", name: "焼き魚と日本酒、しみじみ。",         nameEn: "Grilled Fish & Sake, Heartfelt." },
  { id:  79, file: "omp079.png", name: "コーンスープ、まろやか！",           nameEn: "Corn Soup, Smooth!" },
  { id:  80, file: "omp080.png", name: "オニオンスープ、コクがある！",       nameEn: "Onion Soup, Deep Flavor!" },
  { id:  81, file: "omp081.png", name: "モンブラン、とろける",               nameEn: "Mont Blanc, Melty" },
  { id:  82, file: "omp082.png", name: "アップルパイ、さっぱり",             nameEn: "Apple Pie, Light & Fresh" },
  { id:  83, file: "omp083.png", name: "みかんゼリー、ぷるぷる",             nameEn: "Mandarin Jelly, Jiggly" },
  { id:  84, file: "omp084.png", name: "いちごタルト、あまい",               nameEn: "Strawberry Tart, Sweet" },
  { id:  85, file: "omp085.png", name: "抹茶ロールケーキ、濃厚",             nameEn: "Matcha Roll Cake, Rich" },
  { id:  86, file: "omp086.png", name: "バウムクーヘン、しっとり",           nameEn: "Baumkuchen, Moist" },
  { id:  87, file: "omp087.png", name: "大福、もちもち",                     nameEn: "Daifuku, Chewy" },
  { id:  88, file: "omp088.png", name: "ベビーカステラ、ふかふか",           nameEn: "Baby Castella, Fluffy" },
  { id:  89, file: "omp089.png", name: "どらやき、おいしい",                 nameEn: "Dorayaki, Delicious" },
  { id:  90, file: "omp090.png", name: "わらび餅、ぷるぷる",                 nameEn: "Warabi Mochi, Jiggly" },
  { id:  91, file: "omp091.png", name: "あんぱん、あんこ",                   nameEn: "Anpan, Red Bean Bread" },
  { id:  92, file: "omp092.png", name: "チョコクッキー、チョコ",             nameEn: "Chocolate Cookie, Chocolatey" },
  { id:  93, file: "omp093.png", name: "カスタードたいやき、あまい",         nameEn: "Custard Taiyaki, Sweet" },
  { id:  94, file: "omp094.png", name: "ソフトクリーム、とろける",           nameEn: "Soft Serve Ice Cream, Melty" },
  { id:  95, file: "omp095.png", name: "ショートケーキ、ふわふわ",           nameEn: "Strawberry Shortcake, Fluffy" },
  { id:  96, file: "omp096.png", name: "チーズケーキ、濃厚",                 nameEn: "Cheesecake, Rich" },
  { id:  97, file: "omp097.png", name: "チュロス、おいしい",                 nameEn: "Churros, Delicious" },
  { id:  98, file: "omp098.png", name: "パンケーキ、ふかふか",               nameEn: "Pancakes, Fluffy" },
  { id:  99, file: "omp099.png", name: "いちご大福、もちもち",               nameEn: "Strawberry Daifuku, Chewy" },
  { id: 100, file: "omp100.png", name: "カヌレ、カリカリ",                   nameEn: "Canelé, Crispy" },
  { id: 101, file: "omp101.png", name: "フレンチトースト、あまい",           nameEn: "French Toast, Sweet" },
  { id: 102, file: "omp102.png", name: "マカロン、カラフル",                 nameEn: "Macarons, Colorful" },
  { id: 103, file: "omp103.png", name: "パウンドケーキ、しっとり",           nameEn: "Pound Cake, Moist" },
  { id: 104, file: "omp104.png", name: "チョコフォンデュ、とろーり",         nameEn: "Chocolate Fondue, Gooey" },
  { id: 105, file: "omp105.png", name: "幸せホットケーキとゼリー",           nameEn: "Happy Hotcake & Jelly" },
  { id: 106, file: "omp106.png", name: "フルーツサンド、きれい",             nameEn: "Fruit Sandwich, Pretty" },
  { id: 107, file: "omp107.png", name: "カンノーリ、とろーり",               nameEn: "Cannoli, Creamy" },
  { id: 108, file: "omp108.png", name: "杏仁豆腐、さっぱり",                 nameEn: "Almond Tofu, Refreshing" },
  { id: 109, file: "omp109.png", name: "プリン、プルプル",                   nameEn: "Pudding, Jiggly" },
  { id: 110, file: "omp110.png", name: "メロンソーダ、しゅわしゅわ",         nameEn: "Melon Soda, Fizzy" },
  { id: 111, file: "omp111.png", name: "いちごパフェ、最高！",               nameEn: "Strawberry Parfait, The Best!" },
  { id: 112, file: "omp112.png", name: "シュークリーム、いっぱい",           nameEn: "Cream Puffs, Plenty" },
  { id: 113, file: "omp113.png", name: "たいやき、おいしい？",               nameEn: "Taiyaki, Tasty?" },
  { id: 114, file: "omp114.png", name: "クレープ、たべる",                   nameEn: "Crepe, Let's Eat" },
  { id: 115, file: "omp115.png", name: "和パフェ、きれい",                   nameEn: "Japanese Parfait, Beautiful" },
  { id: 116, file: "omp116.png", name: "かき氷、つめたい",                   nameEn: "Shaved Ice, Ice Cold" },
  { id: 117, file: "omp117.png", name: "和菓子、うれしい",                   nameEn: "Wagashi, Delightful" },
  { id: 118, file: "omp118.png", name: "アイス、さいこー",                   nameEn: "Ice Cream, Awesome" },
  { id: 119, file: "omp119.png", name: "メロンパン、ふかふか",               nameEn: "Melon Bread, Fluffy" },
  { id: 120, file: "omp120.png", name: "みたらし団子、もちもち",             nameEn: "Mitarashi Dango, Chewy" },
];
